site_name: My Technical Note
site_url: https://my-technical-note.netlify.app/
site_author: Allen Liu
site_description: "My technical note written with MkDocs"
repo_url: "https://github.com/RyukerLiu/My-Technical-Note"
edit_uri: "edit/main/docs/"

theme:
  name: null
  custom_dir: cinder
  colorscheme: github
  highlightjs: true

nav:
  - Home: index.md
  - Learning Note:
    - Aggreate vs Annotate Sum: Learning Note/Aggreate vs Annotate Sum.md
    - OO多型與架構: Learning Note/OO_ploy.md
    - CORS: Learning Note/CORS.md
    - CSRF: Learning Note/CSRF.md
    - Design Patterns: Learning Note/Design Patterns.md
    - DNS Domain and Subdomain: Learning Note/DNS Domain and Subdomain.md
    - Kubenetes Port: Learning Note/Kubenetes Port.md
    - 如何使用 plantuml: Learning Note/如何使用 plantuml.md
  - Resources:
    - 12 Factor: Resources/12 Factor.md
    - AI: Resources/AI.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
